SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1 AND NAME IS NOT NULL
ORDER BY NAME;

--HAVING 절을 쓰므로써 GROUP BY에 제한을 둔다
--HAVING절은 SELECT문에 들어가는 것만 쓸 수 있는지 알았지만 COUNT(*)이런 식으로 써도 사용 가능