-- 재귀쿼리 사용 notion에 자세히 정리
WITH RECURSIVE NUMBER AS (
	SELECT 0 AS N
	UNION ALL
	SELECT N+1
	FROM NUMBER
	WHERE N < 23
)

SELECT N, COUNT(ANIMAL_OUTS.DATETIME) AS COUNT
FROM NUMBER
LEFT JOIN ANIMAL_OUTS
ON HOUR(ANIMAL_OUTS.DATETIME) = NUMBER.N
GROUP BY N;